travis:
  secure:
    BINSTAR_TOKEN: rXchSSeyaAUE+nRPiLPaeHI0uxCZhBIwC1Q1jXab8mmMTXaY7Jdru2BsGoU4vhneZ/r92iipgpiwjJZC/fScDohSWsvVLZUa9DNZwbDaedbDburP1A978FXdCuJlwgVMwN69v6aRmLIwMG4uBW5nszb/ha4GwmrDEF2H/5ingPLqBg58Fn7h1EdqbP449MBH//OCGKX86qMSwKB8OjeB4QBfDCfktC7dOgLmZJWzzpBVp2izNrZZhHYWw01roh6+WjvcIEvpxRnuk1jLF0xgq+SATTuuAYiq7jolU+TYVI+L9xQGVHpBNl+wEG08lBYgoSFhL0IbRsO1zAnKZxu1d3Omlj0fuKs61mOd1Fz0DnkaKG4Ko6MAPHMezwVgIO3heK5KR6n8EbkaoD5BXO6XYZI9N9DyBa1YGb8Y/bTm6zPmDtHyDBhPx3svbQhj+q1EO+yuxFCwFFhTEG+iwZOzFhfPjV3WOrKxIX0QAwPrs82rW6vYL1kGY4EsKeNzWQsLBwMFJkBHszzm/y70AWwf94ik6MlrQGPwCPrRMd13bJwV6LhN3+nt+H7JnJznayP+8x69gn0W7RqBuXz8nAYK3pLrNlcd8oCSZXOnd7zwm8BxZdCWKAtrJcr5UhgwGxLtiWOeq/yzi72QqCSNmbDMYNM2jaYGiMscS+wGwGH0g5g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
